### ISSUE TITLE
是否支持facebook 竞价？

### ISSUE THREAD

**Issue by JacoblLee** [AdTiming/OpenMediation-Android#11]
是否支持facebook 竞价？还是需要取得facebook 授权才可以？

**Comment by OpenMediationProject** [comment]
支持。但是您自建的inhouse平台需要获得Facebook授权。

**Comment by JacoblLee** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
