### ISSUE TITLE
如何将sdk打成aar包或者jar类库形式

### ISSUE THREAD

**Issue by momo88xiaowu** [AdTiming/OpenMediation-Android#5]

**Comment by android9527** [comment]
您好，可以在终端中进入到对应项目目录执行 gradle bundleReleaseAar 命令，或者在 Android Studio 中打开 Gradle 窗口双击对应项目的 bundleReleaseAar 任务即可打包生成 aar，生成的文件会在 build/outputs/aar 目录下。
![image](https://user-images.githubusercontent.com/3029720/114965578-75e91700-9ea3-11eb-8c6b-754eed762579.png)

**Comment by momo88xiaowu** [comment]
你好，请教如何将相关的library也打包到一个jar 或aar中。比如用广点通tecent_cn  aar 包 和 头条穿山甲tiktok_cn aar 包 ，open mediation sdk aar包，这三个打成一个aar或者jar。用到哪个广告aar就与sdk 打包为一体。
