### ISSUE TITLE
sdk初始化设置inithost问题

### ISSUE THREAD

**Issue by qyzhaojinxi** [AdTiming/OpenMediation-Android#7]
我看代码中初始化接口原版格式为：https://s.openmediation.com/init?v=1&plat=1&sdkv=2.3.3&k=gwsQFNL6ef0WZoIWP1rtHg0gokviPjOX

假如我设置自定义域名，那inithost应该是怎么样的？我看代码中接口并没有设置/init这个path，还是说我直接在设置inithost时就设置为https://xxxxxxxx/init这样的形式？

**Comment by zwmessi** [comment]
> 我看代码中初始化接口原版格式为：https://s.openmediation.com/init?v=1&plat=1&sdkv=2.3.3&k=gwsQFNL6ef0WZoIWP1rtHg0gokviPjOX
> 
> 假如我设置自定义域名，那inithost应该是怎么样的？我看代码中接口并没有设置/init这个path，还是说我直接在设置inithost时就设置为[https://xxxxxxxx/init这样的形式？](https://xxxxxxxx/init%E8%BF%99%E6%A0%B7%E7%9A%84%E5%BD%A2%E5%BC%8F%EF%BC%9F)

是的，只需要按照https://xxxxxxxx/init的格式，补全域名设置给初始化的位置即可

**Comment by qyzhaojinxi** [comment]
好的，谢谢
